apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-service-ingress
  namespace: jenkins
  annotations:
    # ГЛАВНОЕ: сообщаем Ingress, что бэкенд ждет HTTPS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Разрешаем самоподписанные сертификаты Argo
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    # Отключаем ограничение на размер загружаемых файлов
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: jenkins.test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 80 # Используйте 443 порт для HTTPS связи внутри кластера
