apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd # Обязательно тот же, где установлен Argo CD
spec:
  rules:
    - host: argo.test.local # Ваш домен
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server # Имя основного сервиса Argo
                port:
                  number: 8080
